name: lucasthorn
favicon: null
layout_spectrum: 0.84043
typography_spectrum: 0.56389
title: Lucas Thorn
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#140d15'
    - '#fffac0'
    - '#896c44'
    - '#48412f'
    - '#891515'
  brandStrength: 0.25
  lightness: 0.6873933142051101
  saturation: 0.7650864103343338
  rhythmicContrast: 1
purpose: []
