name: lucasthorn
favicon: null
layout_spectrum: 0.4863920302595943
typography_spectrum: 0.6981211416423321
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1110'
    - '#bccfd6'
    - '#fffeff'
    - '#9baaaf'
    - '#444967'
  brandStrength: 0.23951958725228906
  lightness: 0.6873933142051101
  saturation: 0.7650864103343338
  rhythmicContrast: 0.5036889014299959
purpose: []
